#                                         ** Section - A **

### A1. Why are NumPY arrays generally preferred over plain Python lists for numerical computation in AI/ML workloads?


NumPy arrays are mainly used for numerical data and calculations. They can perform operations on many values at the same time, which is usually faster than processing values one by one with Python lists. NumPy also provides useful mathematical functions such as sum, mean, minimum, and maximum.

### A2. Explain vectorization. Why does replacing an explicit Python loop with a vectorized NumPy operation matter with large datasets?

Vectorization means performing an operation on many values at the same time instead of processing each value one by one using a loop. NumPy supports vectorized operations, which makes numerical calculations simpler and usually faster. This becomes especially useful when we work with large datasets because we can avoid writing explicit Python loops for every element.

### A3. For compatible 2D arrays A and B, explain A * B vs A @ B. Describe one neural-network situation for each.

A * B performs multiplication element by element, so values in the same positions are multiplied. A @ B performs matrix multiplication using rows and columns. In neural networks, * can be used for element-wise operations such as applying a mask, while @ is commonly used to multiply input features with weight matrices in a neural-network layer.

### A4. What is broadcasting in NumPy? State the general rule used to decide whether arrays of different shapes can be combined element-wise.

Broadcasting is a feature in NumPy that allows us to perform element-wise operations on arrays with different but compatible shapes. NumPy compares the dimensions starting from the right side. The dimensions are compatible when they are equal or when one of them is 1. Broadcasting is useful because it allows us to perform calculations without manually repeating or copying values.

### A5.Explain flatten() vs ravel(). In a memory-constrained application processing large images, which would you prefer and why?

Both flatten() and ravel() can convert an array into a one-dimensional array. The main difference is that flatten() creates a copy of the data, while ravel() tries to return a view of the original data when possible. When working with large images and limited memory, I would prefer ravel() because it can avoid creating an extra copy and therefore use less additional memory.

### A6.For a 2D array, explain axis=0 and axis=1 in an aggregation function such as np.sum() or np.mean(). Illustrate with a small example.

In a 2D NumPy array, axis=0 performs the calculation down the rows and gives a result for each column. axis=1 performs the calculation across the columns and gives a result for each row. For example, if a = [[10,20,30],[40,50,60]], np.sum(a, axis=0) gives [50,70,90], while np.sum(a, axis=1) gives [60,150].

In [ ]:
import numpy as np
import pandas as pd


In [11]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(a)
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

[[10 20 30]
 [40 50 60]]
[50 70 90]
[ 60 150]


### A7. Why is it important to normalize or standardize numerical features before training most ML models? Explain normalization vs standardization.

Normalization and standardization help put numerical features on a similar scale before training a model. This can prevent features with large values from having too much influence. Normalization usually scales values to a fixed range such as 0 to 1. Standardization changes the values so that they have a mean of 0 and a standard deviation of 1.

Normalization - fixed range (usually 0 to 1)

Standardization - mean 0, standard deviation 1

### A8. Why do functions such as np.nanmean() exist? What happens if np.mean() is used directly on data containing NaN?

np.mean() calculates the average of all values, but if the array contains a NaN, the result will normally also be NaN.

np.nanmean() is useful when the data contains missing values represented by NaN. It calculates the mean while ignoring NaN values. In contrast, np.mean() normally returns NaN if any NaN value is present.

### A9. In the ML convention X.shape = (samples, features), explain how this extends to a batch of RGB images. Write the exact shape for 64 RGB images of size 128 × 128.

X.shape tells us the number of samples and features in a dataset.
For example, (100, 5) means there are 100 samples and 5 features.
For RGB images, the shape includes the number of images, height, width, and color channels.
Therefore, 64 RGB images of size 128 × 128 have the shape (64, 128, 128, 3).

### A10.Why is reproducibility important in ML experiments, and how does np.random.default_rng(seed) help achieve it?

Reproducibility means getting the same results when an ML experiment is run again with the same settings.
It is important for checking results, debugging, and comparing experiments fairly.
np.random.default_rng(seed) creates a random number generator using a fixed seed value.
Using the same seed produces the same sequence of random values each time.

# ** Section - B **
B1.
 
a = np.array([1, 2, 3])​

b = np.array([[1], [2], [3]])​

print((a + b).shape)​

OUTPUT: (3, 3)

B2. 
x = np.arange(1, 7).reshape(2, 3)
print(x[:, 1])

OUTPUT: 
[2, 3]

B3. 
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr % 10 == 0])

OUTPUT:
[10 20]

B4. 
m = np.array([[1, 2], [3, 4]])
print(m.T @ m)

OUTPUT:
[[10 14]
 [14 20]]

B5. data = np.array([1, 2, np.nan, 4])
print(np.mean(data), np.nanmean(data))

OUTPUT:
2.33

B6. x = np.array([10, 20, 30])
y = np.where(x > 15, 1, 0)
print(y)

OUTPUT:
[0 1 1]

B7. a = np.zeros((3, 4))
print(a.ndim, a.size)

OUTPUT:
2, 12

B8. arr = np.arange(1, 13).reshape(3, 4)
print(arr[::-1, ::-1])

OUTPUT:
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]

# ** Section - C **
### C1. Given a 1D NumPy array of exam scores, use np.where() to produce labels 'P' (score >= 40) or 'F' (score < 40).

In [1]:
import numpy as np

scores = np.array([35, 45, 67, 28, 80])
result = np.where(scores >= 40, 'P', 'F')
print(result)

['F' 'P' 'P' 'F' 'P']


Explanation:
 np.where() checks each score and gives P when the score is 40 or above; otherwise, it gives F.

### C2. Write a function standardize(x) that takes a 1D NumPy array and returns its z-score standardized version using only NumPy.

In [2]:
def standardize(x):
    mean = np.mean(x)
    std = np.std(x)
    return (x - mean) / std
x = np.array([10, 20, 30, 40, 50])
print(standardize(x))

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


Explanation: 
The function finds the mean and standard deviation of the array and uses them to convert each value into its standardized form.

### C3. Given two 2D NumPy arrays representing separate batches with the same number of features, combine them using an appropriate NumPy stacking function and print the resulting shape.

In [3]:
batch1 = np.array([[1, 2], [3, 4]])
batch2 = np.array([[5, 6], [7, 8], [9, 10]])
combined = np.vstack((batch1, batch2))
print(combined)
print(combined.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(5, 2)


Explanation:
 np.vstack() combines the two batches vertically because they have the same number of features (columns).

### C4.Given X with shape (100, 5), compute column-wise mean and standard deviation and standardize the matrix in one vectorized expression.

In [4]:
X = np.random.default_rng(42).random((100, 5))
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_standardized = (X - mean) / std
print(X_standardized.shape)

(100, 5)


Explanation: 
axis=0 calculates the mean and standard deviation for each column, and broadcasting applies these values to all rows.

### C5. Implement y_pred = X @ w + b for a feature matrix X, weight vector w and bias b. Then compute MSE using y_true.

In [5]:
X = np.array([[1, 2], [3, 4], [5, 6]])
w = np.array([0.5, 1.0])
b = 2
y_true = np.array([4, 7, 10])
y_pred = X @ w + b
mse = np.mean((y_true - y_pred) ** 2)
print("Predictions:", y_pred)
print("MSE:", mse)

Predictions: [ 4.5  7.5 10.5]
MSE: 0.25


Explanation: X @ w + b calculates the predicted values, and MSE calculates the average squared difference between the actual and predicted values.

#### C6. Using np.random.default_rng() with a fixed seed, generate 10 samples and 3 features from a normal distribution. Print the shape and confirm identical results with the same seed

In [6]:
rng1 = np.random.default_rng(42)
data1 = rng1.normal(size=(10, 3))
rng2 = np.random.default_rng(42)
data2 = rng2.normal(size=(10, 3))
print(data1.shape)
print(np.array_equal(data1, data2))

(10, 3)
True


Explanation: 
The fixed seed produces the same random values each time, so both arrays are identical and the shape is (10, 3).

### C7. Given a grayscale image as a 2D NumPy array with pixel values in [0, 255], normalize the values to [0, 1] using min-max normalization.

In [7]:
image = np.array([
    [0, 128],
    [200, 255]
])
normalized = (image - image.min()) / (image.max() - image.min())
print(normalized)

[[0.         0.50196078]
 [0.78431373 1.        ]]


Explanation: 
Min-max normalization changes the smallest pixel value to 0, the largest to 1, and scales the remaining values between 0 and 1.

### C8. Given 4 RGB images of shape (28, 28, 3), stored as shape (4, 28, 28, 3), compute the average pixel value of each image across height, width and channels. State the axis argument and why.

In [8]:
images = np.random.default_rng(42).random((4, 28, 28, 3))
average = np.mean(images, axis=(1, 2, 3))
print(average.shape)

(4,)


Explanation: 
axis=(1, 2, 3) averages the height, width, and RGB channels while keeping the 4 images separate, giving one average value for each image.

# ** SECTION - D ** 
# D1. Data Preprocessing Pipeline


Q. You are given a raw 1D or 2D NumPy array containing NaN values.​

Describe, step by step, the NumPy operations you would apply to:​

(a) detect missing values,​

(b) handle them appropriately and justify your strategy, and​

(c) normalize or standardize the clean data before it is fed to a model.​

Implement the full pipeline in code on a sample array of your own choosing, including at least one NaN.​



In [ ]:
import numpy as np

data = np.array([10, 20, np.nan, 40, 50])
print("Missing values:", np.isnan(data))
mean_value = np.nanmean(data)
clean_data = np.where(np.isnan(data), mean_value, data)
standardized = (clean_data - np.mean(clean_data)) / np.std(clean_data)
print("Clean data:", clean_data)
print("Standardized data:", standardized)

Missing values: [False False  True False False]
Clean data: [10. 20. 30. 40. 50.]
Standardized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


Explanation:

(a) Detect Missing Values

First, I use np.isnan() to check whether the array contains any missing (NaN) values.
np.isnan(data)

(b) Handle Missing Values

For numerical data, I can replace the missing value with the mean of that column. I use np.nanmean() because it calculates the mean without considering the NaN value.

(c) Standardize the Data

After filling the missing values, I standardize the data. Standardization changes the values so that they are on a similar scale.

The formula is:

Standardized value = (value - mean) / standard deviation

This can help the machine learning model work better when different features have different ranges.


# D2. Image Batch Understanding 
1, Explain, with correct NumPy shapes, how a single RGB image differs from a batch of RGB images.​

2, Write code to create a dummy batch of 16 images of size 64 × 64 using random pixel values.​

3, Compute the average image of the batch, meaning the element-wise mean across all 16 images.​

4,State the shape of your result and explain why.​

In [6]:
import numpy as np

batch = np.random.randint(0, 256, size=(16, 64, 64, 3))
print("Batch shape:", batch.shape)
average_image = np.mean(batch, axis=0)
print("Average image shape:", average_image.shape)

Batch shape: (16, 64, 64, 3)
Average image shape: (64, 64, 3)


Explanation: axis=0 averages corresponding pixels across all 16 images while preserving the height, width, and RGB channels.

# D3.Debug the Model Code

In [7]:
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0, 0.2])

b = 2.0

y_pred = X @ w + b

y_true = np.array([10, 20, 30])

mse = np.mean(y_true - y_pred ** 2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

Explonation:

There are two bugs in the code. 

First, X has shape (3, 2), so w must have 2 values, but the given w has 3 values. 

Second, the MSE formula is incorrect because y_pred ** 2 is calculated first due to operator precedence. 

We need to first subtract y_pred from y_true, then square the difference and calculate the mean

In [8]:
#Corrected code
import numpy as np

X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0])
b = 2.0
y_pred = X @ w + b
y_true = np.array([10, 20, 30])
mse = np.mean((y_true - y_pred) ** 2)
print("Predictions:", y_pred)
print("MSE:", mse)

Predictions: [4.5 6.  7.5]
MSE: 244.16666666666666


Explanation

X contains 3 data samples and 2 features, so w contains 2 weights. The @ operator calculates the weighted values, and b is added as the bias. Finally, MSE is calculated by finding the difference between actual and predicted values, squaring the differences, and taking their mean.

# ** Section - E ** {Bonus}
E1. Per-Column Min–Max Normalization

Implement min-max normalization for a 2D feature matrix on a per-column (per-feature) basis, rather than using a single global 
min/max for the whole array. Your solution must be fully vectorized, with no explicit loops over rows or columns.​

In [ ]:
import numpy as np

X = np.array([
    [10, 100],
    [20, 200],
    [30, 300]
])
X_min = np.min(X, axis=0)
X_max = np.max(X, axis=0)
X_normalized = (X - X_min) / (X_max - X_min)
print("Column minimums:", X_min)
print("Column maximums:", X_max)
print("Normalized matrix:")
print(X_normalized)

Column minimums: [ 10 100]
Column maximums: [ 30 300]
Normalized matrix:
[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


Explanation:

Here, each column is normalized separately using its own minimum and maximum value. axis=0 finds the minimum and maximum for each feature column. Broadcasting allows these values to be used for all rows without using loops. The normalized values are between 0 and 1.

# E2. Three-Level Score Classification

Given a 1D array of exam scores, use a single vectorized expression (no if/else statements and no explicit loops) to classify 
each score as:​

Fail (< 40), Average (40–70 inclusive), or Excellent (> 70).​

Hint: You may need to nest or combine np.where() calls.​

In [10]:
import numpy as np

scores = np.array([25, 40, 55, 70, 85, 95])
result = np.where(
    scores < 40,
    "Fail",
    np.where(scores <= 70, "Average", "Excellent")
)
print("Scores:", scores)
print("Classification:", result)

Scores: [25 40 55 70 85 95]
Classification: ['Fail' 'Average' 'Average' 'Average' 'Excellent' 'Excellent']


Explanation:

I used nested np.where() to classify all scores without using loops or if/else statements. Scores below 40 are classified as Fail, scores from 40 to 70 are classified as Average, and scores above 70 are classified as Excellent. Because np.where() works on the complete array at once, the solution is vectorized.